services:
  postgres:
    image: postgres:16
    container_name: crud_noframework
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_noframework
    ports:
      - 5432:5432

  pgadmin:
    container_name: crud_noframework_pgadmin
    image: dpage/pgadmin4:latest
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
